language:
  - scala

scala:
  - 2.12.4

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate coverageReport
  - codecov